import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [initalNum, setNum] = useState(0)
  const [fromSEKtoGBP, setSEKtoGBP] = (useState(0))
  const [fromDKKtoGBP, setDKKtoGBP] = (useState(0))

  const bwithington1990 = 'BnkKiQ50dU8RHJleLMtKS256pLiv3Oeg'
  const benandlou22 = 'AiflhGODQCgfZtCZoizhjn8cGI1cQu4T'

  var myHeaders = new Headers();
  myHeaders.append("apikey", benandlou22);

  var requestOptions = {
    method: 'GET',
    redirect: 'follow',
    headers: myHeaders
  };

  // https://api.apilayer.com/currency_data/convert?to={to}&from={from}&amount={amount}
  // https://api.apilayer.com/exchangerates_data/convert?to=GBP&from=SEK&amount=${initalNum}`, requestOptions)

  const convert = () => {
    fetch(`https://api.apilayer.com/exchangerates_data/convert?to=GBP&from=SEK&amount=${initalNum}`, requestOptions)
      .then(response => response.json())
      .then(result =>
        setSEKtoGBP(result.result)
      )
      .catch(error => console.log('error', error));
    fetch(`https://api.apilayer.com/exchangerates_data/convert?to=GBP&from=DKK&amount=${initalNum}`, requestOptions)
      .then(response => response.json())
      .then(result =>
        setDKKtoGBP(result.result)
      )
      .catch(error => console.log('error', error));
  }

  const handleClick = () => {
    convert(initalNum)
  }

  function handleChange(e) {
    console.log(e.target.value)
    setNum(e.target.value)
  }


  return (
    <>
      <Head>
        <title>Currency Converter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Me personal currency converter</h1>
        <div className={styles.center}>
          <h2>Enter Amount:</h2>
          <div className={styles.thirteen}>
            <input name={initalNum} onChange={handleChange} />
          </div>
          <button onClick={handleClick}>Convert</button>
        </div>



        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              SEK<span>-&gt;</span><span>GBP</span>
            </h2>
            <p style={{ fontSize: "3rem" }} className={inter.className}>
              {fromSEKtoGBP}
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              DKK<span>-&gt; </span><span>GBP</span>
            </h2>
            <p className={inter.className}>
              {fromDKKtoGBP}
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
